version: 0.2
os: linux
files:
  - source: /
    destination: /opt/react
    overwrite: true
  #- source: /scripts
  #  destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
      
#permissions:
##  - object: /home/ubuntu/start_server.sh
#    pattern: "**"
#    owner: root
#    mode: "755"
#    
#hooks:
#  #ApplicationStop:
#    #- location: scripts/stop_server.sh
#    #  timeout: 300
#    #  runas: root
#  ApplicationStart:
#    - location: scripts/start_server.sh
#      timeout: 300
#      runas: root
