version: 0.2
os: linux
files:
  - source: /build
    destination: /opt/react
  - source: /scripts
    destination: /home/ubuntu

permissions:
  - object: /home/ubuntu/start_server.sh
    pattern: "**"
    owner: root
    mode: "755"
    
hooks:
  #ApplicationStop:
    #- location: scripts/stop_server.sh
    #  timeout: 300
    #  runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
